### ISSUE TITLE
Invalid address was provided: failed to lookup address information: Name or service not known

### ISSUE THREAD

**Issue by myusernameis69** [evilsocket/legba#16] opened 2023-11-05 13:09 UTC
root@debian:~/thc-hydra# legba ssh -t @/root/thc-hydra/ssh_targets.txt --username @/root/thc-hydra/users.txt --password @/root/thc-hydra/passwords.txt --output /root/thc-hydra/LEGBA_SSH_GOOD.txt --output-format text --timeout 30000 --retries 5 --retry-time 1000 --concurrency 5 --jitter-min 500 --jitter-max 500
legba v0.3.0

[INFO ] targeting @/root/thc-hydra/ssh_targets.txt
[INFO ] username -> string '@/root/thc-hydra/users.txt'
[INFO ] password -> string '@/root/thc-hydra/passwords.txt'

[INFO ] tasks=5 mem=19.7 MiB done=0 (0.00%) speed=0 reqs/s
[INFO ] tasks=5 mem=19.9 MiB done=0 (0.00%) speed=0 reqs/s
[INFO ] tasks=5 mem=19.9 MiB done=0 (0.00%) speed=0 reqs/s
[INFO ] tasks=5 mem=19.9 MiB done=0 (0.00%) speed=0 reqs/s
[INFO ] tasks=5 mem=19.9 MiB done=0 (0.00%) speed=0 reqs/s
[INFO ] tasks=5 mem=19.9 MiB done=0 (0.00%) speed=0 reqs/s
[ERROR] attempt 5/5: Invalid address was provided: failed to lookup address information: Name or service not known
[INFO ] tasks=5 mem=19.9 MiB done=1 (100.00%) errors=1 speed=0 reqs/s
[INFO ] runtime 7.090724367s

Content of ssh_targets.txt is:
ip
ip
ip
etc..

**Comment by evilsocket** [comment] 2023-11-05 13:51
dude for real? this is a duplicate of #15

**Comment by evilsocket** [comment] 2023-11-05 13:52
1. multi mode is not released yet
2. no need to use @ for --username and --password

**Closed by evilsocket** 2023-11-05 13:51 UTC
